export const NAVIGATOR_SCREEN = {
  HOME: "HOME",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  REGISTER_DETAIL: "REGISTER_DETAIL",
  QUESTION: "QUESTION",
  QUESTION_DETAIL: "QUESTION_DETAIL",
  SPLASH: "SPLASH",
  ADMIN: "ADMIN",
  RESULT: "RESULT",
  REPO: "REPO",
  REPO_DETAIL: "REPO_DETAIL",
  NOTE: "NOTE",
  NOTE_DETAIL: "NOTE_DETAIL",
  NOTE_FORM: "NOTE_FORM",
};

export const QUESTION_SCREEN = {
  LOP_HOC: "LOP_HOC",
  VIEC_HOC: "VIEC_HOC",
  THI_CU: "THI_CU",
};
